spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cshr
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate # validate schema on run.  Updates handled by Liquibase.
    properties:
        hibernate:
            search:
                default:
                    directory_provider: filesystem
                    indexBase: /target/indexpath
  location:
    service:
      url: http://location-service.dev.cshr-gov.uk/findlocation/{searchTerm} # will be overridden by an env variable
server:
  port: 8080
liquibase:
    change-log: classpath:/changelog.xml
security:
    oauth2:
        resource:
            filter-order: 3
