spring:
  wcndatafeed:
    oauth:
      client: csrapiclient
      secret: csrapiclient
      user: wcn
      password: wcn
server:
  port: 8990
security:
    oauth2:
        resource:
            filter-order: 3
